version: '3'

services:
  blockchain-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    command: >
      sh -c "
      npm --prefix /app/backend install &&
      node /app/backend/index.js"
